### ISSUE TITLE
Add instructions on how to run

### ISSUE THREAD

**Issue by cmauf** [brianstrauch/solitaire-tui#13]
Add instructions on how to run to README.md

**Comment by brianstrauch** [comment]
The README includes the following command:
```
go install github.com/brianstrauch/solitaire-tui@latest
```

You should be able to install the game with that command after downloading and setting up Go 1.19! Then type `solitaire-tui`  from your terminal and it should run. Let me know if you need help!

**Comment by cmauf** [comment]
I installed it using the command you mentioned. But typing `solitaire-gui` just yields `[command](zsh: command not found: solitaire-tui)` I'm on Manjaro 5.15

**Comment by stdevel** [comment]
The binary should have been installed to `~/go/bin/solitaire-tui` - drop the following line to your `~/.bashrc` to alter your `PATH` variable after the next shell relaunch:

```
export PATH="$PATH:~/go/bin"
```

**Comment by cmauf** [comment]
Did not work with the instructions you gave, but I created an alias in my `.zshrc` that runs the executable. Thanks for your help!

Point still stands that some instructions in the README would be nice :smile:
